version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: publis_npm
        displayName: Npm Publish
        nodeVersion: 16.14.2
        commands:
          - '# access token'
          - npm config set //registry.npmjs.org/:_authToken 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
          - '# 执行编译命令'
          - npm publish
        caches: []
        notify: []
        strategy:
          retry: '0'
